name: Build and push Docker image

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  CURRENT_VERSION: 29.4.0
  BUILD_NUMBER: 0
  LATEST_UBUNTU_VERSION: "24.04"

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - ubuntu_version: "22.04"
            ubuntu_name: "jammy"
          - ubuntu_version: "24.04"
            ubuntu_name: "noble"
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install sysbox
        run: |
          cd /tmp
          wget https://downloads.nestybox.com/sysbox/releases/v0.7.0/sysbox-ce_0.7.0-0.linux_amd64.deb
          sudo dpkg -i sysbox-ce_0.7.0-0.linux_amd64.deb

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build standalone image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          push: false
          load: true
          file: Dockerfile
          platforms: linux/amd64
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu_version }}
          tags: |
            otter-aerospace/ubuntu-dind:${{ matrix.ubuntu_name }}-test

      - name: Test standalone image (privileged mode)
        run: |
          chmod +x test.sh
          ./test.sh --mode privileged --use-systemd false --image-name ghcr.io/otter-aerospace/ubuntu-dind:${{ matrix.ubuntu_name }}-test

      - name: Test standalone image (sysbox-runc mode)
        run: |
          ./test.sh --mode sysbox-runc --use-systemd false --image-name ghcr.io/otter-aerospace/ubuntu-dind:${{ matrix.ubuntu_name }}-test

      - name: Build and push standalone image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          push: true
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu_version }}
          tags: |
            ghcr.io/otter-aerospace/ubuntu-dind:${{ matrix.ubuntu_name }}-${{ env.CURRENT_VERSION }}
            ghcr.io/otter-aerospace/ubuntu-dind:${{ matrix.ubuntu_name }}-${{ env.CURRENT_VERSION }}-r${{ env.BUILD_NUMBER }}
            ghcr.io/otter-aerospace/ubuntu-dind:${{ matrix.ubuntu_name }}-latest
            ${{ matrix.ubuntu_version == env.LATEST_UBUNTU_VERSION && 'ghcr.io/otter-aerospace/ubuntu-dind:latest' || '' }}

      # - name: Build systemd image
      #   uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
      #   with:
      #     push: false
      #     load: true
      #     file: Dockerfile.systemd
      #     platforms: linux/amd64
      #     build-args: |
      #       UBUNTU_VERSION=${{ matrix.ubuntu_version }}
      #     tags: |
      #       ghcr.io/otter-aerospace/ubuntu-dind:${{ matrix.ubuntu_name }}-systemd-test

      # - name: Test systemd image (privileged mode)
      #   run: |
      #     ./test.sh --mode privileged --use-systemd true --image-name ghcr.io/otter-aerospace/ubuntu-dind:${{ matrix.ubuntu_name }}-systemd-test

      # - name: Test systemd image (sysbox-runc mode)
      #   run: |
      #     ./test.sh --mode sysbox-runc --use-systemd true --image-name ghcr.io/otter-aerospace/ubuntu-dind:${{ matrix.ubuntu_name }}-systemd-test

      # - name: Build and push systemd image
      #   uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
      #   with:
      #     push: true
      #     file: Dockerfile.systemd
      #     platforms: linux/amd64,linux/arm64
      #     build-args: |
      #       UBUNTU_VERSION=${{ matrix.ubuntu_version }}
      #     tags: |
      #       ghcr.io/otter-aerospace/ubuntu-dind:${{ matrix.ubuntu_name }}-systemd-${{ env.CURRENT_VERSION }}
      #       ghcr.io/otter-aerospace/ubuntu-dind:${{ matrix.ubuntu_name }}-systemd-${{ env.CURRENT_VERSION }}-r${{ env.BUILD_NUMBER }}
      #       ghcr.io/otter-aerospace/ubuntu-dind:${{ matrix.ubuntu_name }}-systemd-latest
      #       ${{ matrix.ubuntu_version == env.LATEST_UBUNTU_VERSION && 'ghcr.io/otter-aerospace/ubuntu-dind:systemd-latest' || '' }}
